### ISSUE TITLE
Stop working after Avalonia 0.10.9 on Windows

### ISSUE THREAD

**Issue by ArtjomP** [Projektanker/Icons.Avalonia#13]
Hello there!
It stopped working after Avalonia 0.10.9 on Windows. The next code showed an icon before and now it doesn't.
` 
<fa:Icon Value="far fa-plus-square" />
`
I updated Avalonia to 0.10.10 & Projektanker.Icons.Avalonia.FontAwesome to 3.2.0.
It didn't help.
Thank you in advance!

**Comment by SebastianRumohr** [comment]
Hi,
thank you for reporting the issue.
The bug is fixed with version [3.4.0](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/3.4.0)
