### ISSUE TITLE
How to get access to icon in c#?

### ISSUE THREAD

**Issue by donnyv** [Projektanker/Icons.Avalonia#15]
I'm using the AuraTabView and I added a tab in code and it has a Icon property that is of type Avalonia.Media.IImage. How would I set that in C# code?

**Comment by SebastianRumohr** [comment]
You could do it like this:
```csharp
using Projektanker.Icons.Avalonia;


var icon = new Icon
{
    Value = "fa-plus"
};

tabView.Icon = icon.DrawingImage;
```

**Comment by SebastianRumohr** [comment]
@OmidID that's right. There is currently no alternative solution other than create an image by yourself. For futute requests please create a new issue. Therefore it's easer to track open issues.
