### ISSUE TITLE
Spinning icons from FontAwesome

### ISSUE THREAD

**Issue by lostmsu** [Projektanker/Icons.Avalonia#22]
Icons like `fa-sync` have spinning option in FontAwesome that animates them: https://fontawesome.com/v5/docs/web/style/animate

I cannot find anything similar here, and adding `fa-sync` style fails.

**Comment by SebastianRumohr** [comment]
I added animations with version [5.4.0](https://www.nuget.org/packages/Projektanker.Icons.Avalonia.FontAwesome/5.4.0)  
To animate the icon add the `Animation` property to your icon:  
```xml
<i:Icon Value="fa-spinner" Animation="Pulse" />
<i:Icon Value="fa-sync" Animation="Spin" />
```
