### ISSUE TITLE
6.1.0-preview1 is referencing Avalonia.Diagnostics

### ISSUE THREAD

**Issue by hez2010** [Projektanker/Icons.Avalonia#23]
6.1.0-preview1 is referencing Avalonia.Diagnostics, which brings huge dependencies on `Microsoft.CodeAnalysis.*` and causes major size regression.

**Comment by SebastianRumohr** [comment]
Fixed with [version 6.2.0-preview-1](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/6.2.0-preview1).
