### ISSUE TITLE
How to use non filed icons?

### ISSUE THREAD

**Issue by michalwitek1232** [Projektanker/Icons.Avalonia#25]
Hi, In my example Avalonia app I want to use following icon:
![obraz](https://user-images.githubusercontent.com/42500203/195902055-5153672a-d0f3-4401-87ad-a6a61f9d478b.png)
But when I'm trying to use following XAML:
```xaml
<i:Icon Value="far fa-clipboard-check" FontSize="15"></i:Icon>
```
I'm getting:
`System.Collections.Generic.KeyNotFoundException: 'FontAwesome Style "Regular" not found!'`

Any idea how to use this version of that icon?

**Comment by mariusmg** [comment]
I'm facing the same issue :
System.Collections.Generic.KeyNotFoundException: 'FontAwesome Icon "file-o" not found!'

Any plans to update icons.json and add all the free FontAwesome icons  ?

**Comment by SebastianRumohr** [comment]
@michalwitek1232 the icon `fa-regular fa-clipboard-check` is a pro icon and not available. Only free icons are available.

**Comment by SebastianRumohr** [comment]
@mariusmg i can't the icon `file-o` online https://fontawesome.com/search?q=file-o. Are you sure the icon exists?

**Comment by mariusmg** [comment]
Hi Sebastian,

Yes, it's this one https://fontawesome.com/v4/icon/file-o
But it's v4, i assume these are not supported ?

**Comment by SebastianRumohr** [comment]
@mariusmg no v4 is not supported. The current supoorted version is v6 (https://github.com/Projektanker/Icons.Avalonia#icon-providers)

**Comment by mariusmg** [comment]
Thank you for confirmation and kudos for creating this library.
