### ISSUE TITLE
consider using source generator for parsing json

### ISSUE THREAD

**Issue by ivanjx** [Projektanker/Icons.Avalonia#27]
net 7 comes with native aot compiling. this library does not work really well with it since this parses json for the FontAwesome package. the json deserializer needs to use source generator feature that was introduced back in net 6. even after integrating source generator for the json parsing, since this uses `JsonStringEnumConverter`, an entry inside `rd.xml` is required:
```
<Directives>
	<Application>
                ....
		<Assembly Name="Projektanker.Icons.Avalonia.FontAwesome">
			<Type Name="Projektanker.Icons.Avalonia.FontAwesome.FontAwesomeIconProvider" Dynamic="Required All"></Type>
		</Assembly>
		<Assembly Name="System.Text.Json">
			<Type Name="System.Text.Json.Serialization.Converters.EnumConverter`1[[Projektanker.Icons.Avalonia.FontAwesome.Style,Projektanker.Icons.Avalonia.FontAwesome]]" Dynamic="Required All" />
		</Assembly>
	</Application>
</Directives>
```

related: https://github.com/dotnet/runtime/issues/73124

**Comment by SebastianRumohr** [comment]
I have no experience with code generators in .NET. 
Is this possible with current target framework `netstandard2.0`.
Could you share an example how to implement the feature requested? Or perhaps even create a PR?

**Comment by ivanjx** [comment]
it is fairly easy if you already using STJ for json stuff.

https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator

**Comment by SebastianRumohr** [comment]
Should be done with version [5.7.0](https://www.nuget.org/packages/Projektanker.Icons.Avalonia.FontAwesome/5.7.0).  
Could you try it?

**Comment by ivanjx** [comment]
sorry i havent been able to test it since i am no longer working on the project with this dependency. anyone else who has tested that and works may close this issue.
