### ISSUE TITLE
TypeInitializer exception thrown on Avalonia 11.0.0-preview

### ISSUE THREAD

**Issue by X9VoiD** [Projektanker/Icons.Avalonia#29]
When using `Projektanker.Icons.Avalonia.Icon` on a project using Avalonia 11.0.0, the program throws the following exception:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Projektanker.Icons.Avalonia.Icon' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Visuals, Version=0.10.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.
```

**Comment by SebastianRumohr** [comment]
You have to use the preview version of `Projektanker.Icons.Avalonia`. Use [Projektanker.Icons.Avalonia 6.4.0-preview5](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/6.4.0-preview5) with Avalonia 11.0.0-preview5.
