### ISSUE TITLE
Question regarding true compatibility with FontAwesome

### ISSUE THREAD

**Issue by xD0135** [Projektanker/Icons.Avalonia#30]
First of all, thank you for your project, it seems quite useful. 👍 

I'm trying a simple example where I want to use a font similar to [this](https://fontawesome.com/v6/icons/shield?s=regular&f=classic):
```
<i class="fa-regular fa-shield"></i>
```
In `MainWindow.axaml` I have:
```
<i:Icon Value="fa-regular fa-shield" />
```
But when building the project I'm faced with the following exception:
```
System.Collections.Generic.KeyNotFoundException: 'FontAwesome Style "Regular" not found!'
```
I have both of these packages installed:
```
    <PackageReference Include="Projektanker.Icons.Avalonia" Version="5.9.0" />
    <PackageReference Include="Projektanker.Icons.Avalonia.FontAwesome" Version="5.9.0" />
```
Am I missing something? Thanks in advance for the help.

**Comment by SebastianRumohr** [comment]
Thank you. 

Only Fontawesome Free icons are supported. 
To use a shield icon please check for the free ones: https://fontawesome.com/search?q=shield&o=r&m=free

I should update the exception message to be more helpful.

**Comment by xD0135** [comment]
Makes sense. Thank you for taking the time to review and reply.
