### ISSUE TITLE
[Question] How to grey out icons when button is disabled?

### ISSUE THREAD

**Issue by sn4k3** [Projektanker/Icons.Avalonia#38]
Using your demo and by disable buttons it grey out the icons as expected.
![image](https://github.com/Projektanker/Icons.Avalonia/assets/113281/f6bbe232-0287-4107-aec6-f2c4f40d252a)

However, I can't get same behavior on my application:
![image](https://github.com/Projektanker/Icons.Avalonia/assets/113281/fe2fe1b9-5bad-4a28-a3f3-89a5687dd503)

After analyzing your demo app, I can't find any associate style to make this happen... What I'm missing?
The difference is my application use Bindings for IsEnable while your is using style, but I don't know if that makes the difference.

**Comment by SebastianRumohr** [comment]
I tried to reproduce your bug.  
I updated the Demo project to use a basic view model. Some buttons are disabled by style others by binding. Unfortunately. I can't reproduce the bug.  
The icon color uses the `Foreground` brush of it's parent. Maybe your buttons do not change their `Foreground` brush when disbled?

**Comment by sn4k3** [comment]
> The icon color uses the Foreground brush of it's parent. Maybe your buttons do not change their Foreground brush when disbled?

They do, I'm using the FluentTheme. See the middle button which have the letter "D", it's disabled and got greyed instead of active black

![image](https://github.com/Projektanker/Icons.Avalonia/assets/113281/2633ad06-c880-4dae-92fb-60bf2bd04cbd)

In my whole [app](https://github.com/sn4k3/UVtools) I can't get it to work like that, no matter if is a <i> or <button><i></button>

NOTE: I tried to switch to the normal theme and that now shows as expected! The "problem" is when using fluent theme...

**Comment by SebastianRumohr** [comment]
I tried to reproduce it with the [demo app](https://github.com/Projektanker/Icons.Avalonia/tree/main/demo). It is already using the [Fluent Theme](https://docs.avaloniaui.net/docs/next/basics/user-interface/styling/themes/fluent). I checked again and can't reproduce the bug. I checked with the [Simple Theme](https://docs.avaloniaui.net/docs/next/basics/user-interface/styling/themes/simple) as well.
Can you send me a minimal app to reproduce the bug?
Did you try to use Avalonia 11 already?

**Comment by sn4k3** [comment]
> Did you try to use Avalonia 11 already?

Yes, same problem...
I temporary fix it with ``Icon:disabled` -> Opacity=0.3`

> Can you send me a minimal app to reproduce the bug?

Will try to do that. Also you can try my [app repo](https://github.com/sn4k3/UVtools) (But that is still on v0.10)

**Comment by sn4k3** [comment]
I found the actual problem (my fault), it was a leftover on my theme style which was forcing Foreground color:

```xml
    <Style Selector="i|Icon">
        <Setter Property="Foreground" Value="#1E1E1E" />
    </Style>
```

Removing such fixed the problem and now it fades correctly based on stock themes.
Thanks for looking. Make sure to take a peak at [PathIcon](https://docs.avaloniaui.net/docs/next/reference/controls/detailed-reference/path-icon)

**Comment by SebastianRumohr** [comment]
I'm glad you figured it out. 
Thanks for the tip using PathIcon. I will check it out.
