### ISSUE TITLE
Is it possible to display an icon and text on a button at the same time?

### ISSUE THREAD

**Issue by cmot17** [Projektanker/Icons.Avalonia#39]
I tried to add an icon to a button that already has a text label, and the icon doesn't show up until I get rid of the text. Is that intended behavior?

**Comment by SebastianRumohr** [comment]
Yes. That is intended behavior.  
The attached icon will replace the entire content of the button it's attached to (e.g. `<Button i:Attached.Icon="fa-brands fa-github" >This will be replaced</Button>`).  
To display an icon and text you have to use the icon component like so:
```xaml
<Button>
  <StackPanel Spacing="4" Orientation="Horizontal">
    <i:Icon Value="fa-check" />
    <TextBlock>Some Text</TextBlock>
  </StackPanel>
</Button>
```
