### ISSUE TITLE
Sign assemblies with a strong key?

### ISSUE THREAD

**Issue by sn4k3** [Projektanker/Icons.Avalonia#55]
Do you consider in sign assemblies with snk?

"Problem:"
```
6>CSC : warning CS8002: Referenced assembly 'Projektanker.Icons.Avalonia, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
6>CSC : warning CS8002: Referenced assembly 'Projektanker.Icons.Avalonia.FontAwesome, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
6>CSC : warning CS8002: Referenced assembly 'Projektanker.Icons.Avalonia.MaterialDesign, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

**Comment by SebastianRumohr** [comment]
After reading [How to: Sign an assembly with a strong name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name) I think signing the assemblies with a strong name is not worth the effort. 
But please feel free to change my mind.

**Comment by sn4k3** [comment]
That article makes it very hard and it is signing manually by command line...

Where the steps:

1. Open visual studio developer cmd and generate a strong key, eg: `sn -k Icons.Avalonia.snk` and put it at `src` folder
2. On your Directory.Build.props, add:
```xml
<SignAssembly>True</SignAssembly>
<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Icons.Avalonia.snk</AssemblyOriginatorKeyFile>
```
3. Done!

Now compiling will generate all your libraries signed by default. 


Notes:

Signed libraries / apps will now be happy about using your library but also not signed apps can still use your library without any problem.

**Comment by SebastianRumohr** [comment]
Okay. Thank you.
Done with [version 8.1.0](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/8.1.0)
