### ISSUE TITLE
Unable to dynamically change colour of the icon

### ISSUE THREAD

**Issue by MioPedersen** [Projektanker/Icons.Avalonia#6]
I've attempted pretty much everything, but I cannot for the life of me change the color dynamically, is there something Im missing?

**Comment by SebastianRumohr** [comment]
Could share your code? Otherwise it's hard to for me to help.

**Comment by SebastianRumohr** [comment]
With [version 3.1.1](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/3.1.1) the bug is fixed.
