### ISSUE TITLE
How to easily view the icons available in the project?

### ISSUE THREAD

**Issue by zy1075984** [Projektanker/Icons.Avalonia#66]
1.How to easily view the icons available in the project?
2.The width and height settings for the icons are ineffective and remain in their original size, as shown below.
`   <i:Icon Value="fa-spinner" Animation="Spin" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" MinWidth="32" MinHeight="32"/>`

**Comment by SebastianRumohr** [comment]
> 1.How to easily view the icons available in the project?

Click on the links the [**Description** column in the NuGet section of the README](https://github.com/Projektanker/Icons.Avalonia#nuget).

> 2. The width and height settings for the icons are ineffective and remain in their original size, as shown below.

The size of the `Icon` is set by it's `FontSize` property. Please take a look at the [Demo](https://github.com/Projektanker/Icons.Avalonia/blob/main/demo/MainWindow.axaml) or as shown below.
```xml
  <i:Icon Value="fa-spinner" 
          Animation="Spin" 
          FontSize="24" />
```
I will update the [**Usage** section in the README](https://github.com/Projektanker/Icons.Avalonia#usage) with an example of how to change the size of the icons.
