### ISSUE TITLE
Icons are not updated when a button is enabled or disabled

### ISSUE THREAD

**Issue by sakya** [Projektanker/Icons.Avalonia#7]
When a button is enabled or disabled the icon is not updated.

The first button is enabled, the second is disabled
![image](https://user-images.githubusercontent.com/289552/128860237-937ddedf-9c8c-42c1-a754-fa301829e5c9.png)

After pressing "toggle buttons enabled" the icons are not updated
![image](https://user-images.githubusercontent.com/289552/128860296-024d49b2-f837-4f0c-98f0-e552bf265959.png)

After pressing the second button the icon is updated
![image](https://user-images.githubusercontent.com/289552/128860721-c53275d5-440c-4a7d-aa7f-f0936dd1dc6f.png)

Test project
[Test.zip](https://github.com/Projektanker/Icons.Avalonia/files/6961312/Test.zip)

**Comment by sakya** [comment]
I tried both using Attached.Icon (the first button) or setting the icon as the content of the button (the second button), the result is the same

**Comment by SebastianRumohr** [comment]
Thank you for filing this issue.
Your test project really did help.
With [version 3.1.1](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/3.1.1) the bug is fixed.
